version: '3'

services:
    db:
        image: postgres
        ports:
            - "5436:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=sqllearndb
        volumes:
            - ./dbs/postgres-data:/var/lib/postgresql
    backend:
        container_name: online_notebook_backend
        build: ./application
        command: bash -c "
                python manage.py makemigrations && python manage.py migrate &&
                python manage.py runserver --insecure 0.0.0.0:8000";
        volumes:
             - ./application:/application
        ports:
            - "8005:8000"

        depends_on:
            - db
#    frontend:
#        container_name: frontend
#        build:
#            context: ./frontend
#            dockerfile: Dockerfile
#        volumes:
#            - ./frontend:/app
#            - node-modules:/app/node_modules
#        ports:
#            - "3001:3000"
#        environment:
#            - REACT_APP_API_HOST=94.250.249.177
#            - REACT_APP_API_SCHEMA=http
#            - REACT_APP_API_PORT=8001
#            - PORT=3000
#        depends_on:
#            - backend

volumes:
  node-modules:
